[build]
  command = "pnpm build"
  publish = "dist/portfolio-2026/browser"

[build.environment]
  NPM_FLAGS = "--dangerously-allow-built-dependencies=@parcel/watcher,esbuild,lmdb,msgpackr-ext,msgpackr-extract,sharp"
